### ISSUE TITLE
Severe memory leak in pokedex screen in dev branch

### ISSUE THREAD

**Issue by tsweeney256** [TeamBrock/Pokedex#15]
Tested in Debian Linux

Only step needed to reproduce the bug is to press F2 to go into the poxedex screen from the main menu. While having the screen active, the program continually leaks memory until it's closed or it crashes the whole computer. It stops leaking the memory if you press F1 to go back to the menu screen, however this doesn't actually free any of the leaked memory.

**Comment by stephenap07** [comment]
Yup, fixed this in my dev branch. This happens because of text rendering on the pokedex screen continuously creates SDL_Texture resources without freeing them. Thanks for testing.

**Comment by tsweeney256** [comment]
okay cool. I'll go and close this then.
